version: '3.9'

services:
  frontend:
    container_name: frontend_motorshop
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on: 
      - api_motorshop

  api_motorshop:
    container_name: api_motorshop
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
        
    depends_on:
      - db_motorshop
    volumes:
      - .:/backend/app

  db_motorshop:
    image: postgres:14-alpine
    env_file: ./backend/.env
    ports: 
      - 5435:${POSTGRES_PORT}

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: 
    driver: local
